name: CI
on: [push, pull_request]
env:
  CI: true
  CI_SNAPSHOT_RELEASE: +publishSigned
  SCALA_VERSION: 2.12.11
jobs:
  validate:
    name: Scala ${{ matrix.scala }}, Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8]
        scala: [2.12.11]
    env:
      SCALA_VERSION: ${{ matrix.scala }}
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Check formatting
        run: sbt ++$SCALA_VERSION scalafmtCheckAll
      - name: Check SBT formatting
        run: sbt ++$SCALA_VERSION scalafmtSbtCheck
      - name: Compile
        run: sbt ++$SCALA_VERSION test:compile
      - name: Test
        run: sbt ++$SCALA_VERSION test
      - name: Scaladoc
        run: sbt ++$SCALA_VERSION doc
